# Generated by Django 3.2 on 2021-05-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='image',
            field=models.ImageField(upload_to='static/images/rooms'),
        ),
    ]
