# Generated by Django 3.2 on 2021-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRM', 'Confirm'), ('RETURNED', 'Returned'), ('CANCEL', 'Cancel')], default='PENDING', max_length=10),
        ),
    ]
