# Generated by Django 3.2 on 2021-05-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRM', 'Confirm'), ('OCCUPIED', 'Occupied'), ('RETURNED', 'Returned'), ('CANCEL', 'Cancel')], default='PENDING', max_length=10),
        ),
    ]
