# Generated by Django 3.2 on 2021-05-21 03:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20210521_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('discount', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100, null=True)),
                ('create_date', models.DateField(default=datetime.date(2021, 5, 21))),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.voucher'),
        ),
    ]
