# Generated by Django 3.2 on 2021-05-26 01:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_comments_create_date'),
        ('hotel', '0009_alter_voucher_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.signup'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 5, 26)),
        ),
    ]
