# Generated by Django 3.2 on 2021-05-27 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='voucher',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.voucher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 5, 27)),
        ),
    ]
