# Generated by Django 3.2 on 2021-05-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_booking_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.voucher'),
        ),
    ]
