# Generated by Django 3.2 on 2021-06-04 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_voucher_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 6, 4)),
        ),
    ]
