# Generated by Django 3.2 on 2021-06-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20210604_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description_home',
            field=models.CharField(default='', max_length=200),
        ),
    ]
