# Generated by Django 3.2 on 2021-06-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_categories_description_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description_home',
            field=models.CharField(default='', max_length=500),
        ),
    ]
